config/routes.rb
Rails.application.routes.draw do
  resources :websites
  root to: 'websites#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
    flash[:notice] = "afad"
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.fetch(:website, {}).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/_flash-messages.html.erb
flash

app/views/layouts/_header.html.erb
header cont

app/views/layouts/_main-pannel.html.erb
<div id="main-pannel" class="container-fluid">
  <div id="header">
    <%= render 'layouts/header' %>
  </div>
  <div id="flash-messages">
    <%= render 'layouts/flash-messages' %>
  </div>
  <div id="main-content">
    main-content
  </div>
</div>

app/views/layouts/_side-pannel.html.erb
<div id="side-pannel">
  <div class="span2">
    side-bar
  </div>
  <div id="side-pannel-toggle" class="navbar-light">
    <button class="navbar-toggler hidden-md-up" type="button"></button>
  </div>
</div>

<% content_for :foot do %>
<script>
$('#side-pannel-toggle button').click(function () {
  $('#wrapper').toggleClass('side-pannel-open');
});
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="he">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Bonjo</title>

</head>

<body class="nav-md footer_fixed">
  <div class="container body">
    <div class="main_container">
      <div id="sidebar" class="col-md-3 right_col">
        <div class="right_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index-rtl.html" class="site_title"><i class="fa fa-paw"></i> <span>Bonjo</span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>ברוך הבא,</span>
              <h2>דניאל</h2>
            </div>

            <div class="clearfix"></div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">


            <ul class="nav side-menu">
              <li><a><i class="fa fa-home"></i>דף הבית<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/">לינק 1</a></li>
                  <li><a href="/2">לינק 2</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-edit"></i>עריכה<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/edit">לינק 1</a></li>
                  <li><a href="/edit">לינק 2</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-desktop"></i>אלמנטים<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/desktop">לינק 1</a></li>
                  <li><a href="/desktop">לינק 2</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-table"></i>טבלאות<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/table">לינק 1</a></li>
                  <li><a href="/table">לינק 2</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-bar-chart-o"></i>אנליטיקס<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/chart">לינק 1</a></li>
                  <li><a href="/chart">לינק 2</a></li>
                </ul>
              </li>
              <li><a><i class="fa fa-clone"></i>תבחר מה אני בבקשה<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/clone">לינק 1</a></li>
                  <li><a href="/clone">לינק 2</a></li>
                </ul>
              </li>
            </ul>
          </div>


          </div>
          <!-- /sidebar menu -->

        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle hidden-md hidden-lg">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-left">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <img src="images/img.jpg" alt="">Daniel Macbubi
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-left">
                  <li><a href="javascript:;">פרופיל</a></li>
                  <li>
                    <a href="javascript:;">
                      <span class="badge bg-red pull-left">50%</span>
                      <span>הגדרות</span>
                    </a>
                  </li>
                  <li><a href="javascript:;">עזרה</a></li>
                  <li><a href="login.html"><i class="fa fa-sign-out pull-left"></i>התנתק</a></li>
                </ul>
              </li>


              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div class="left_col" role="main">

      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          ממשק הניהול נבנה בעזרת <a href="https://colorlib.com">Colorlib</a> כל הזכויות שמורות לBonjo
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

  <!-- jQuery -->
  <!-- <script src="../vendors/jquery/dist/jquery.min.js"></script> -->
  <!-- Bootstrap -->
  <!-- <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script> -->
  <!-- Custom Theme Scripts -->
  <!-- <script src="../build/js/custom.min.js"></script> -->


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_for(website) do |f| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= website.errors.count %></h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>